# Generated by Django 5.1.1 on 2024-10-06 05:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_doctor_doctor_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorapply',
            name='type',
        ),
        migrations.RemoveField(
            model_name='doctorapply',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='text',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='text',
            name='sender',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default=uuid.uuid4, max_length=16),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='DoctorApply',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
