# Generated by Django 5.1.1 on 2024-10-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_remove_message_doctor_remove_doctorapply_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=16),
        ),
    ]
